name: "Build iOS app"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    
    - name: bazel setup
      uses: bazelbuild/setup-bazelisk@v3

    - name: Mount bazel cache  # Optional
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Build
      run: bazel build //Draw:Draw

    - name: Test
      run: | # --cpu=ios_x86_64 resolve CI problem
        pgrep Simulator | xargs kill || true
        
        bazel test //DrawTests:DrawTests --test_output=all --cpu=ios_x86_64
