name: "Build iOS app"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
    - name: checkout repository
      uses: actions/checkout@master

    - name: Build
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //Draw:Draw

    - name: Test
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //DrawTests:DrawTests --test_output=all
